In [2]:
import pandas as pd
from pathlib import Path

In [3]:
DATA_DIR = Path.cwd().parent / "feature_repo" / "data"
dfc = pd.read_parquet(DATA_DIR / "ames_processed.parquet")
dfc

,Fireplaces,Kitchen.Qual,Remod.Age,Open.Porch.SF,Garage.Age,Lot.Area,Full.Bath,BsmtFin.SF.1,Garage.Cars,X1st.Flr.SF,Exter.Qual,Total.Bsmt.SF,Garage.Area,Gr.Liv.Area,Overall.Qual,SalePrice
0,2.0,2,50.0,62.0,50.0,4.502017,1.0,639.0,2.0,1656.0,2,1080.0,528.0,1656.0,3,5.332438
2,0.0,1,52.0,36.0,52.0,4.154333,1.0,923.0,1.0,1329.0,2,1329.0,312.0,1329.0,3,5.235528
5,1.0,1,12.0,36.0,12.0,3.999043,2.0,602.0,2.0,926.0,2,926.0,470.0,1604.0,3,5.291147
15,1.0,0,7.0,36.0,7.0,4.728386,3.0,1416.0,3.0,1690.0,0,1650.0,841.0,3279.0,5,5.730782
17,1.0,0,0.0,0.0,0.0,4.056676,1.0,1445.0,3.0,1856.0,1,1856.0,834.0,1856.0,6,5.595972
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2904,0.0,2,9.0,48.0,9.0,3.846337,2.0,1243.0,4.0,1368.0,2,1288.0,784.0,1368.0,4,5.332438
2905,0.0,2,8.0,125.0,8.0,3.653213,2.0,897.0,2.0,1216.0,2,1216.0,402.0,1216.0,3,5.214844
2906,0.0,2,8.0,199.0,8.0,3.653213,2.0,1201.0,2.0,1337.0,2,1237.0,405.0,1337.0,3,5.186108
2915,1.0,2,27.0,0.0,37.0,4.126586,1.0,119.0,1.0,1360.0,2,1104.0,336.0,1360.0,2,5.146128
2929,1.0,2,12.0,48.0,13.0,3.983491,2.0,758.0,3.0,996.0,2,996.0,650.0,2000.0,4,5.274158

In [4]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1155 entries, 0 to 2929
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Fireplaces     1155 non-null   float64
 1   Kitchen.Qual   1155 non-null   int64
 2   Remod.Age      1155 non-null   float64
 3   Open.Porch.SF  1155 non-null   float64
 4   Garage.Age     1155 non-null   float64
 5   Lot.Area       1155 non-null   float64
 6   Full.Bath      1155 non-null   float64
 7   BsmtFin.SF.1   1155 non-null   float64
 8   Garage.Cars    1155 non-null   float64
 9   X1st.Flr.SF    1155 non-null   float64
 10  Exter.Qual     1155 non-null   int64
 11  Total.Bsmt.SF  1155 non-null   float64
 12  Garage.Area    1155 non-null   float64
 13  Gr.Liv.Area    1155 non-null   float64
 14  Overall.Qual   1155 non-null   int64
 15  SalePrice      1155 non-null   float64
dtypes: float64(13), int64(3)
memory usage: 153.4 KB